service: ats-integration-ms

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev
  useDotenv: true
  environment:
    ZOHO_CLIENT_ID: ${env:ZOHO_CLIENT_ID, ''}
    ZOHO_CLIENT_SECRET: ${env:ZOHO_CLIENT_SECRET, ''}
    ZOHO_REFRESH_TOKEN: ${env:ZOHO_REFRESH_TOKEN, ''}
    ZOHO_DC: ${env:ZOHO_DC, 'com'}

functions:
  getJobs:
    handler: handler.get_jobs
    events:
      - http:
          path: jobs
          method: get
          cors: true

  createCandidate:
    handler: handler.create_candidate
    events:
      - http:
          path: candidates
          method: post
          cors: true

  getApplications:
    handler: handler.get_applications
    events:
      - http:
          path: applications
          method: get
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: false
